-- Insert User
INSERT INTO USERS (EMAIL, PASSWORD, STATUS) VALUES ('rafael.lopreti@gmail.com', '$2a$10$/9ERQ8she2xY4rlzlOSfIOlPbrjB/1vwUlafgODBCwHwKAKBG11/e', 'ACTIVE');
INSERT INTO USERS (EMAIL, PASSWORD, STATUS) VALUES ('test@gmail.com', '$2a$10$/9ERQ8she2xY4rlzlOSfIOlPbrjB/1vwUlafgODBCwHwKAKBG11/e', 'ACTIVE');
INSERT INTO USERS (EMAIL, PASSWORD, STATUS) VALUES ('test2@gmail.com', '$2a$10$/9ERQ8she2xY4rlzlOSfIOlPbrjB/1vwUlafgODBCwHwKAKBG11/e', 'ACTIVE');
INSERT INTO USERS (EMAIL, PASSWORD, STATUS) VALUES ('admin@gmail.com', '$2a$10$/9ERQ8she2xY4rlzlOSfIOlPbrjB/1vwUlafgODBCwHwKAKBG11/e', 'ACTIVE');
-- All passwords are Abc@1234, but they are encrypted

-- Insert Address
INSERT INTO ADDRESS (USER_ID, CITY, COUNTRY, NEIGHBORHOOD, NUMBER, STREET, ZIP_CODE)
VALUES (1, 'SP', 'Brazil', 'Default Neighborhood', '123', 'Default Street', '12345678');

INSERT INTO ADDRESS (USER_ID, CITY, COUNTRY, NEIGHBORHOOD, NUMBER, STREET, ZIP_CODE)
VALUES (2, 'SP', 'Brazil', 'Default Neighborhood', '321', 'Default Street', '87654321');

-- Insert People
INSERT INTO PEOPLE (ADDRESS_ID, USER_ID, NAME, TAXPAYER_REGISTRY, CATEGORY, PROFILE_IMAGE)
VALUES (1, 1, 'Rafael Lopreti', '111.222.333-44', 'STUDENT', 'https://media.licdn.com/dms/image/v2/D4D03AQGoP0Sy2K_APQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1695260915011?e=1736380800&v=beta&t=mxvBovvLTxzwIpcSclTq7X_o_YiAGB8pufQMM74sAJ0');

INSERT INTO PEOPLE (ADDRESS_ID, USER_ID, NAME, TAXPAYER_REGISTRY, CATEGORY, PROFILE_IMAGE)
VALUES (2, 2, 'Allan Rafael', '111.222.333-45', 'TEACHER', 'https://static.vecteezy.com/system/resources/previews/009/292/244/non_2x/default-avatar-icon-of-social-media-user-vector.jpg');

---- Insert Roles
INSERT INTO ROLES (ID, NAME) VALUES (1, 'GET');
INSERT INTO ROLES (ID, NAME) VALUES (2, 'PATCH');
INSERT INTO ROLES (ID, NAME) VALUES (3, 'POST');
INSERT INTO ROLES (ID, NAME) VALUES (4, 'PUT');
INSERT INTO ROLES (ID, NAME) VALUES (5, 'DELETE');

---- Insert User Roles
INSERT INTO USERS_ROLES (ROLES_ID, USERS_ID) VALUES (1, 4);
INSERT INTO USERS_ROLES (ROLES_ID, USERS_ID) VALUES (2, 4);
INSERT INTO USERS_ROLES (ROLES_ID, USERS_ID) VALUES (3, 4);
INSERT INTO USERS_ROLES (ROLES_ID, USERS_ID) VALUES (4, 4);
INSERT INTO USERS_ROLES (ROLES_ID, USERS_ID) VALUES (5, 4);