package com.lopreti.university.domain.valueObjects;

public enum GlobalErrorCodes {

    STUDENT_NOT_FOUND_ERROR_CODE("UNICODE-001"),
    STUDENT_ALREADY_EXISTS_ERROR_CODE("UNICODE-002"),
    TEACHER_NOT_FOUND_ERROR_CODE("UNICODE-003"),
    TEACHER_ALREADY_EXISTS_ERROR_CODE("UNICODE-004"),
    CLASSES_NOT_FOUND_ERROR_CODE("UNICODE-005"),
    ADDRESS_NOT_FOUND_ERROR_CODE("UNICODE-006"),
    MORE_THAN_ONE_UPDATE_ERROR_CODE("UNICODE-007"),
    WITHOUT_FIELD_UPDATE_ERROR_CODE("UNICODE-008"),
    NO_VALID_FIELD_ERROR_CODE("UNICODE-009"),
    VALID_CANNOT_BE_EMPTY_ERROR_CODE("UNICODE-010"),
    ADDRESS_ALREADY_EXISTS_ERROR_CODE("UNICODE-011"),
    USER_ALREADY_EXISTS_ERROR_CODE("UNICODE-012"),
    USER_NOT_FOUND_ERROR_CODE("UNICODE-013"),
    EMAIL_ALREADY_EXISTS_ERROR_CODE("UNICODE-014"),
    EMAIL_INVALID_FORMAT_ERROR_CODE("UNICODE-015"),
    PASSWORD_INVALID_FORMAT_ERROR_CODE("UNICODE-016"),
    COURSE_ALREADY_EXISTS_ERROR_CODE("UNICODE-017"),
    COURSE_NOT_FOUND_ERROR_CODE("UNICODE-018"),
    PERIOD_NOT_FOUND_ERROR_CODE("UNICODE-019"),
    CLASS_ALREADY_EXISTS_ERROR_CODE("UNICODE-020"),
    PEOPLE_NOT_FOUND_ERROR_CODE("UNICODE-021"),
    SUBJECT_NOT_FOUND_ERROR_CODE("UNICODE-022"),
    INVALID_REQUEST_BODY_ERROR_CODE("UNICODE-023"),
    SUBJECT_ALREADY_EXISTS_ERROR_CODE("UNICODE-024"),
    FIELD_CANNOT_BE_NULL_ERROR_CODE("UNICODE-025"),
    PEOPLE_CATEGORY_NOT_FOUND_ERROR_CODE("UNICODE-026"),
    PEOPLE_ALREADY_EXISTS_ERROR_CODE("UNICODE-026"),
    USER_STATUS_NOT_FOUND_ERROR_CODE("UNICODE-027"),
    USER_ADDRESS_ALREADY_EXISTS_ERROR_CODE("UNICODE-028"),
    USER_IS_REQUIRED_ERROR_CODE("UNICODE-029"),
    ADDRESS_USER_ALREADY_EXISTS_ERROR_CODE("UNICODE-030"),
    USER_PEOPLE_ALREADY_EXISTS_ERROR_CODE("UNICODE-031");

    private final String code;

    GlobalErrorCodes(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
